trigger:
- main

pool:
  name: Default   # Use your self-hosted agent pool

variables:
  mavenOptions: '-Xmx3072m'

steps:

- script: java -version
  displayName: "Check Java Version"

- script: mvn -version
  displayName: "Check Maven Version"

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
