trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenOptions: '-Xmx3072m'
  javaVersion: '1.17'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '$(javaVersion)'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'